# Generated by Django 5.0.3 on 2024-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_customer_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="cheese",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cheeseName", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pizzaName", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="pizzaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pizzaTypeName", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="toppings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toppingName", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
